Step_10 12.05.2023
COBaOrNotCOBa/LearnEnglishWordsTelegramBot pull request #10
Opened 2023-05-12 14:03 UTC by COBaOrNotCOBa

in progress

2023-05-15 12:54 UTC, COBaOrNotCOBa commented
Нужно будет чуть чуть подчистить от лишнего, и я хочу разделить на этапы, чтобы все слова не шли в перемешку. Так же глядя на все функции с кнопками захотелось создать под них класс. Кнопку основного меню мне кажется нужно вынести к клавиатуре отдельно (сделать отдельный доступ, не все вспомнят про команду /start))

2023-05-15 19:09 UTC, ievetrov requested changes
Все круто!
Сделал кнопки в столбик, кнопку выхода из режима изучения слов.
Давай поправим последнюю проблемку (она неочевидна, но немного поработав с ботом ты ее обнаружишь), смотри коммент

2023-05-15 19:09 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +        val responseString = getUpdates(botToken, lastUpdateId)
Давай сделаем еще небольшую правку. Возможно ты заметил, что бот периодически падает работая на сервере. Сейчас он не защищен он проблем с соединением и от серверных ошибок.
Давай сделаем тут так:
```Kotlin
//      val responseString = getUpdates(botToken, lastUpdateId)
        val result = runCatching { getUpdates(botToken, lastUpdateId) }
        val responseString = result.getOrNull() ?: continue
```

Таким образом при любых ошибках в getUpdates(...) мы будем повторять следующую итерацию цикла и не будем падать

2023-05-16 08:09 UTC, COBaOrNotCOBa commented
вынес сброс статистики в статистику )

2023-05-16 08:13 UTC, COBaOrNotCOBa commented on src/main/kotlin/Telegram.kt
> +        val responseString = getUpdates(botToken, lastUpdateId)
done

2023-05-16 12:45 UTC, ievetrov requested changes

2023-05-16 12:45 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +//                listOf(
Тогда не оставляй закоменченный код

2023-05-16 12:45 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +//      val responseString = getUpdates(botToken, lastUpdateId)
Зачем закоменченная строка?

2023-05-16 12:45 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +//        replyMarkup = ReplyMarkup(
а тут почему убрал? Этот код более универсальный. Просто сделай промежуточную переменную со списком списков (кнопок) и добавь туда меню

2023-05-16 12:51 UTC, COBaOrNotCOBa commented on src/main/kotlin/Telegram.kt
> +//                listOf(
я запасливый хомяк, а вдруг пригодится ))

2023-05-16 13:47 UTC, COBaOrNotCOBa commented
сделал, в прошлой раз не получилось с более универсальным кодом. Сейчас наверное тоже можно сделать чуть лучше чем я написал )

2023-05-16 15:05 UTC, ievetrov approved these changes
Все отлично. Поздравляю!

![Od0](https://github.com/COBaOrNotCOBa/LearnEnglishWordsTelegramBot/assets/34489023/060cb967-e006-4602-ad4c-e60844d6c8ee)


Основная часть работы пройдена, этот бот твой - можешь развивать его как хочешь.
До конца подписки еще остается время, так что свои идеи и ссылки на PR можешь присылать мне в личку в телеграм [@ievetrov](https://t.me/ievetrov) - посмотрю и дам обратную связь.

В целом можешь воплощать и отправлять мне уже озвученые тобой идеи:

- разделить на этапы, чтобы все слова не шли в перемешку
- создать класс для кнопок

Плюс пара идей от меня:

- Добавить возможность показывать картинку в качестве подсказки к изучаемому слову (можно даже делать ее заблюреной - такая фича в телеграме)
- Загрузка своего словаря. Ты нажимаешь кнопку "Добавить слова", бот запрашивает файл. Отправляешь - и словарь пополняется

2023-05-17 06:19 UTC, merged